//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Info.proto
namespace com.lvl6.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitStatsProto")]
  public partial class UnitStatsProto : global::ProtoBuf.IExtensible
  {
    public UnitStatsProto() {}
    

    private int _strength = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }

    private int _defense = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"defense", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defense
    {
      get { return _defense; }
      set { _defense = value; }
    }

    private int _resistance = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"resistance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int resistance
    {
      get { return _resistance; }
      set { _resistance = value; }
    }

    private int _moveSpeed = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"moveSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moveSpeed
    {
      get { return _moveSpeed; }
      set { _moveSpeed = value; }
    }

    private int _attackSpeed = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"attackSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attackSpeed
    {
      get { return _attackSpeed; }
      set { _attackSpeed = value; }
    }

    private int _maxMana = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"maxMana", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxMana
    {
      get { return _maxMana; }
      set { _maxMana = value; }
    }

    private int _maxHealth = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maxHealth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxHealth
    {
      get { return _maxHealth; }
      set { _maxHealth = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullUserStructProto")]
  public partial class FullUserStructProto : global::ProtoBuf.IExtensible
  {
    public FullUserStructProto() {}
    

    private int _userStructId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userStructId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userStructId
    {
      get { return _userStructId; }
      set { _userStructId = value; }
    }

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _structId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"structId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structId
    {
      get { return _structId; }
      set { _structId = value; }
    }

    private long _lastCollectTime = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lastCollectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastCollectTime
    {
      get { return _lastCollectTime; }
      set { _lastCollectTime = value; }
    }

    private com.lvl6.proto.CoordinateProto _coordinates = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"coordinates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto coordinates
    {
      get { return _coordinates; }
      set { _coordinates = value; }
    }

    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }

    private long _purchaseTime = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"purchaseTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long purchaseTime
    {
      get { return _purchaseTime; }
      set { _purchaseTime = value; }
    }

    private long _lastUpgradeTime = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"lastUpgradeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastUpgradeTime
    {
      get { return _lastUpgradeTime; }
      set { _lastUpgradeTime = value; }
    }

    private bool _isComplete = default(bool);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isComplete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isComplete
    {
      get { return _isComplete; }
      set { _isComplete = value; }
    }

    private com.lvl6.proto.FullStructProto _fullStruct = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"fullStruct", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.FullStructProto fullStruct
    {
      get { return _fullStruct; }
      set { _fullStruct = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullStructProto")]
  public partial class FullStructProto : global::ProtoBuf.IExtensible
  {
    public FullStructProto() {}
    

    private int _structId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structId
    {
      get { return _structId; }
      set { _structId = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _income = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"income", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int income
    {
      get { return _income; }
      set { _income = value; }
    }

    private int _storage = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"storage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int storage
    {
      get { return _storage; }
      set { _storage = value; }
    }

    private int _minutesToBuild = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"minutesToBuild", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minutesToBuild
    {
      get { return _minutesToBuild; }
      set { _minutesToBuild = value; }
    }

    private int _minutesToUpgradeBase = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"minutesToUpgradeBase", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minutesToUpgradeBase
    {
      get { return _minutesToUpgradeBase; }
      set { _minutesToUpgradeBase = value; }
    }

    private int _price = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _minLevel = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"minLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> minLevel
    {
      get { return _minLevel; }
    }
  

    private int _xLength = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"xLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int xLength
    {
      get { return _xLength; }
      set { _xLength = value; }
    }

    private int _yLength = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"yLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int yLength
    {
      get { return _yLength; }
      set { _yLength = value; }
    }

    private com.lvl6.proto.StructType _structType = com.lvl6.proto.StructType.TOWN_HALL;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"structType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.StructType.TOWN_HALL)]
    public com.lvl6.proto.StructType structType
    {
      get { return _structType; }
      set { _structType = value; }
    }

    private com.lvl6.proto.ResourceType _upgradeResource = com.lvl6.proto.ResourceType.GOLD;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"upgradeResource", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.ResourceType.GOLD)]
    public com.lvl6.proto.ResourceType upgradeResource
    {
      get { return _upgradeResource; }
      set { _upgradeResource = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CoordinateProto")]
  public partial class CoordinateProto : global::ProtoBuf.IExtensible
  {
    public CoordinateProto() {}
    

    private int _x = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int x
    {
      get { return _x; }
      set { _x = value; }
    }

    private int _y = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MinimumUserProto")]
  public partial class MinimumUserProto : global::ProtoBuf.IExtensible
  {
    public MinimumUserProto() {}
    

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private com.lvl6.proto.PlayerClass _userClass = com.lvl6.proto.PlayerClass.WARRIOR;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userClass", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.PlayerClass.WARRIOR)]
    public com.lvl6.proto.PlayerClass userClass
    {
      get { return _userClass; }
      set { _userClass = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MinimumUserProtoWithLevel")]
  public partial class MinimumUserProtoWithLevel : global::ProtoBuf.IExtensible
  {
    public MinimumUserProtoWithLevel() {}
    

    private com.lvl6.proto.MinimumUserProto _minUserProto = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"minUserProto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.MinimumUserProto minUserProto
    {
      get { return _minUserProto; }
      set { _minUserProto = value; }
    }

    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullUserProto")]
  public partial class FullUserProto : global::ProtoBuf.IExtensible
  {
    public FullUserProto() {}
    

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }

    private com.lvl6.proto.PlayerClass _class = com.lvl6.proto.PlayerClass.WARRIOR;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"class", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.PlayerClass.WARRIOR)]
    public com.lvl6.proto.PlayerClass @class
    {
      get { return _class; }
      set { _class = value; }
    }

    private com.lvl6.proto.UnitStatsProto _stats = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.UnitStatsProto stats
    {
      get { return _stats; }
      set { _stats = value; }
    }

    private long _lastHealthRefillTime = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lastHealthRefillTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastHealthRefillTime
    {
      get { return _lastHealthRefillTime; }
      set { _lastHealthRefillTime = value; }
    }

    private long _lastManaRefillTime = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"lastManaRefillTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastManaRefillTime
    {
      get { return _lastManaRefillTime; }
      set { _lastManaRefillTime = value; }
    }

    private int _gold = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }

    private int _tonic = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"tonic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tonic
    {
      get { return _tonic; }
      set { _tonic = value; }
    }

    private int _gems = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"gems", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int gems
    {
      get { return _gems; }
      set { _gems = value; }
    }

    private int _experience = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"experience", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int experience
    {
      get { return _experience; }
      set { _experience = value; }
    }

    private int _tasksCompleted = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"tasksCompleted", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tasksCompleted
    {
      get { return _tasksCompleted; }
      set { _tasksCompleted = value; }
    }

    private int _battlesWon = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"battlesWon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battlesWon
    {
      get { return _battlesWon; }
      set { _battlesWon = value; }
    }

    private int _battlesLost = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"battlesLost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battlesLost
    {
      get { return _battlesLost; }
      set { _battlesLost = value; }
    }

    private string _referralCode = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"referralCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string referralCode
    {
      get { return _referralCode; }
      set { _referralCode = value; }
    }

    private int _numReferrals = default(int);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"numReferrals", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int numReferrals
    {
      get { return _numReferrals; }
      set { _numReferrals = value; }
    }

    private long _lastLoginTime = default(long);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"lastLoginTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastLoginTime
    {
      get { return _lastLoginTime; }
      set { _lastLoginTime = value; }
    }

    private long _lastLogoutTime = default(long);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"lastLogoutTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastLogoutTime
    {
      get { return _lastLogoutTime; }
      set { _lastLogoutTime = value; }
    }

    private bool _isFake = default(bool);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"isFake", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isFake
    {
      get { return _isFake; }
      set { _isFake = value; }
    }

    private bool _isAdmin = default(bool);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"isAdmin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isAdmin
    {
      get { return _isAdmin; }
      set { _isAdmin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AbilityProto")]
  public partial class AbilityProto : global::ProtoBuf.IExtensible
  {
    public AbilityProto() {}
    

    private int _abilityID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"abilityID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int abilityID
    {
      get { return _abilityID; }
      set { _abilityID = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _manaCost = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"manaCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int manaCost
    {
      get { return _manaCost; }
      set { _manaCost = value; }
    }

    private int _castTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"castTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int castTime
    {
      get { return _castTime; }
      set { _castTime = value; }
    }

    private int _coolDown = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"coolDown", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coolDown
    {
      get { return _coolDown; }
      set { _coolDown = value; }
    }

    private com.lvl6.proto.AbilityProto.AbilityType _abilityType = com.lvl6.proto.AbilityProto.AbilityType.ATTACK;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"abilityType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.AbilityProto.AbilityType.ATTACK)]
    public com.lvl6.proto.AbilityProto.AbilityType abilityType
    {
      get { return _abilityType; }
      set { _abilityType = value; }
    }

    private int _power = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }

    private bool _persist = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"persist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool persist
    {
      get { return _persist; }
      set { _persist = value; }
    }

    private int _lifetime = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"lifetime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int lifetime
    {
      get { return _lifetime; }
      set { _lifetime = value; }
    }

    private int _speed = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int speed
    {
      get { return _speed; }
      set { _speed = value; }
    }

    private float _retarget = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"retarget", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float retarget
    {
      get { return _retarget; }
      set { _retarget = value; }
    }

    private float _size = default(float);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float size
    {
      get { return _size; }
      set { _size = value; }
    }

    private int _shots = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"shots", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int shots
    {
      get { return _shots; }
      set { _shots = value; }
    }

    private int _arc = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"arc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int arc
    {
      get { return _arc; }
      set { _arc = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"AbilityType")]
    public enum AbilityType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK", Value=0)]
      ATTACK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUFF", Value=1)]
      BUFF = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARC_ATTACK", Value=2)]
      ARC_ATTACK = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitProto")]
  public partial class UnitProto : global::ProtoBuf.IExtensible
  {
    public UnitProto() {}
    

    private int _unitID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unitID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int unitID
    {
      get { return _unitID; }
      set { _unitID = value; }
    }

    private com.lvl6.proto.UnitStatsProto _stats = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.UnitStatsProto stats
    {
      get { return _stats; }
      set { _stats = value; }
    }

    private com.lvl6.proto.EquipmentProto _weapon = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"weapon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.EquipmentProto weapon
    {
      get { return _weapon; }
      set { _weapon = value; }
    }

    private com.lvl6.proto.EquipmentProto _armor = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"armor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.EquipmentProto armor
    {
      get { return _armor; }
      set { _armor = value; }
    }

    private com.lvl6.proto.EquipmentProto _amulet = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"amulet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.EquipmentProto amulet
    {
      get { return _amulet; }
      set { _amulet = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private com.lvl6.proto.ColorProto _color = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.ColorProto color
    {
      get { return _color; }
      set { _color = value; }
    }

    private int _mass = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mass", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mass
    {
      get { return _mass; }
      set { _mass = value; }
    }

    private float _size = default(float);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float size
    {
      get { return _size; }
      set { _size = value; }
    }

    private bool _enemy = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"enemy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool enemy
    {
      get { return _enemy; }
      set { _enemy = value; }
    }

    private com.lvl6.proto.UnitProto.LogicSet _logic = com.lvl6.proto.UnitProto.LogicSet.CHASE;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"logic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.UnitProto.LogicSet.CHASE)]
    public com.lvl6.proto.UnitProto.LogicSet logic
    {
      get { return _logic; }
      set { _logic = value; }
    }

    private bool _ranged = default(bool);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"ranged", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ranged
    {
      get { return _ranged; }
      set { _ranged = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _abilityIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"abilityIDs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> abilityIDs
    {
      get { return _abilityIDs; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LogicSet")]
    public enum LogicSet
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CHASE", Value=0)]
      CHASE = 0
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UnitSpawnerProto")]
  public partial class UnitSpawnerProto : global::ProtoBuf.IExtensible
  {
    public UnitSpawnerProto() {}
    

    private int _spawnerID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"spawnerID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int spawnerID
    {
      get { return _spawnerID; }
      set { _spawnerID = value; }
    }
    private readonly global::System.Collections.Generic.List<com.lvl6.proto.UnitProto> _units = new global::System.Collections.Generic.List<com.lvl6.proto.UnitProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"units", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.lvl6.proto.UnitProto> units
    {
      get { return _units; }
    }
  

    private com.lvl6.proto.CoordinateProto _coordinates = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"coordinates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto coordinates
    {
      get { return _coordinates; }
      set { _coordinates = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MissionProto")]
  public partial class MissionProto : global::ProtoBuf.IExtensible
  {
    public MissionProto() {}
    
    private readonly global::System.Collections.Generic.List<int> _spawnerIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"spawnerIDs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> spawnerIDs
    {
      get { return _spawnerIDs; }
    }
  

    private com.lvl6.proto.CoordinateProto _playerPos = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerPos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.CoordinateProto playerPos
    {
      get { return _playerPos; }
      set { _playerPos = value; }
    }

    private com.lvl6.proto.MissionProto.MissionGoal _goal = com.lvl6.proto.MissionProto.MissionGoal.ELIMINATE;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"goal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.MissionProto.MissionGoal.ELIMINATE)]
    public com.lvl6.proto.MissionProto.MissionGoal goal
    {
      get { return _goal; }
      set { _goal = value; }
    }

    private int _length = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"length", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int length
    {
      get { return _length; }
      set { _length = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MissionGoal")]
    public enum MissionGoal
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ELIMINATE", Value=0)]
      ELIMINATE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SURVIVE", Value=1)]
      SURVIVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BOSS", Value=2)]
      BOSS = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentProto")]
  public partial class EquipmentProto : global::ProtoBuf.IExtensible
  {
    public EquipmentProto() {}
    

    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private com.lvl6.proto.EquipmentProto.EquipmentSlot _slot = com.lvl6.proto.EquipmentProto.EquipmentSlot.WEAPON;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"slot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.EquipmentProto.EquipmentSlot.WEAPON)]
    public com.lvl6.proto.EquipmentProto.EquipmentSlot slot
    {
      get { return _slot; }
      set { _slot = value; }
    }

    private com.lvl6.proto.EquipmentProto.EquipmentClass _class = com.lvl6.proto.EquipmentProto.EquipmentClass.PHYSICAL;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"class", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.EquipmentProto.EquipmentClass.PHYSICAL)]
    public com.lvl6.proto.EquipmentProto.EquipmentClass @class
    {
      get { return _class; }
      set { _class = value; }
    }

    private com.lvl6.proto.UnitStatsProto _stats = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stats", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.lvl6.proto.UnitStatsProto stats
    {
      get { return _stats; }
      set { _stats = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"EquipmentSlot")]
    public enum EquipmentSlot
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEAPON", Value=0)]
      WEAPON = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARMOR", Value=1)]
      ARMOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AMULET", Value=2)]
      AMULET = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EquipmentClass")]
    public enum EquipmentClass
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PHYSICAL", Value=0)]
      PHYSICAL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAGICAL", Value=1)]
      MAGICAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WARRIOR", Value=2)]
      WARRIOR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARCHER", Value=3)]
      ARCHER = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAGE", Value=4)]
      MAGE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=5)]
      ALL = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ColorProto")]
  public partial class ColorProto : global::ProtoBuf.IExtensible
  {
    public ColorProto() {}
    

    private int _red = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"red", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int red
    {
      get { return _red; }
      set { _red = value; }
    }

    private int _green = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"green", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int green
    {
      get { return _green; }
      set { _green = value; }
    }

    private int _blue = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"blue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int blue
    {
      get { return _blue; }
      set { _blue = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResourceType")]
    public enum ResourceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD", Value=0)]
      GOLD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TONIC", Value=1)]
      TONIC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GEMS", Value=2)]
      GEMS = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"StructType")]
    public enum StructType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOWN_HALL", Value=0)]
      TOWN_HALL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_COLLECTOR", Value=1)]
      GOLD_COLLECTOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_STORAGE", Value=2)]
      GOLD_STORAGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TONIC_COLLECTOR", Value=3)]
      TONIC_COLLECTOR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TONIC_STORAGE", Value=4)]
      TONIC_STORAGE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLACKSMITH", Value=5)]
      BLACKSMITH = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WIZARD", Value=6)]
      WIZARD = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PlayerClass")]
    public enum PlayerClass
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WARRIOR", Value=0)]
      WARRIOR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARCHER", Value=1)]
      ARCHER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MAGE", Value=2)]
      MAGE = 2
    }
  
}