//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChestRewardProto.proto
namespace com.lvl6.aoc2.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChestRewardProto")]
  public partial class ChestRewardProto : global::ProtoBuf.IExtensible
  {
    public ChestRewardProto() {}
    

    private int _chestID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chestID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chestID
    {
      get { return _chestID; }
      set { _chestID = value; }
    }

    private int _equipID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"equipID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipID
    {
      get { return _equipID; }
      set { _equipID = value; }
    }

    private int _equipChance = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"equipChance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipChance
    {
      get { return _equipChance; }
      set { _equipChance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}