//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CombatRoomProto.proto
namespace com.lvl6.aoc2.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CombatRoomProto")]
  public partial class CombatRoomProto : global::ProtoBuf.IExtensible
  {
    public CombatRoomProto() {}
    

    private int _roomID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }

    private int _dungeon = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dungeon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dungeon
    {
      get { return _dungeon; }
      set { _dungeon = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _monsters = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"monsters", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> monsters
    {
      get { return _monsters; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}