//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: DungeonProto.proto
namespace com.lvl6.aoc2.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DungeonProto")]
  public partial class DungeonProto : global::ProtoBuf.IExtensible
  {
    public DungeonProto() {}
    

    private int _dungeonID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeonID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dungeonID
    {
      get { return _dungeonID; }
      set { _dungeonID = value; }
    }

    private int _levelReq = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"levelReq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int levelReq
    {
      get { return _levelReq; }
      set { _levelReq = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _rooms = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rooms", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> rooms
    {
      get { return _rooms; }
    }
  

    private string _name = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}