//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipmentType.proto
namespace com.lvl6.aoc2.proto
{
    [global::ProtoBuf.ProtoContract(Name=@"EquipmentType")]
    public enum EquipmentType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEAPON", Value=0)]
      WEAPON = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPPER_BODY", Value=1)]
      UPPER_BODY = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOWER_BODY", Value=2)]
      LOWER_BODY = 2
    }
  
}