//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: EquipmentProto.proto
// Note: requires additional types generated from: RarityType.proto
// Note: requires additional types generated from: EquipmentType.proto
// Note: requires additional types generated from: JobType.proto
namespace com.lvl6.aoc2.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EquipmentProto")]
  public partial class EquipmentProto : global::ProtoBuf.IExtensible
  {
    public EquipmentProto() {}
    

    private int _equipID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"equipID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipID
    {
      get { return _equipID; }
      set { _equipID = value; }
    }

    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private com.lvl6.aoc2.proto.EquipmentType _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.lvl6.aoc2.proto.EquipmentType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private int _durability = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"durability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int durability
    {
      get { return _durability; }
      set { _durability = value; }
    }

    private int _attack = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }

    private int _defense = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"defense", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defense
    {
      get { return _defense; }
      set { _defense = value; }
    }

    private int _addHealth = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"addHealth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int addHealth
    {
      get { return _addHealth; }
      set { _addHealth = value; }
    }

    private int _addMana = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"addMana", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int addMana
    {
      get { return _addMana; }
      set { _addMana = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private com.lvl6.aoc2.proto.RarityType _rarity;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"rarity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.lvl6.aoc2.proto.RarityType rarity
    {
      get { return _rarity; }
      set { _rarity = value; }
    }
    private com.lvl6.aoc2.proto.JobType _job;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.lvl6.aoc2.proto.JobType job
    {
      get { return _job; }
      set { _job = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}