//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MonsterRewardProto.proto
namespace com.lvl6.aoc2.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterRewardProto")]
  public partial class MonsterRewardProto : global::ProtoBuf.IExtensible
  {
    public MonsterRewardProto() {}
    

    private int _monsterID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"monsterID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monsterID
    {
      get { return _monsterID; }
      set { _monsterID = value; }
    }

    private int _equipIDs = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"equipIDs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipIDs
    {
      get { return _equipIDs; }
      set { _equipIDs = value; }
    }

    private int _equipDropChance = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"equipDropChance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipDropChance
    {
      get { return _equipDropChance; }
      set { _equipDropChance = value; }
    }

    private int _itemIDs = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"itemIDs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemIDs
    {
      get { return _itemIDs; }
      set { _itemIDs = value; }
    }

    private int _itemDropChance = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"itemDropChance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemDropChance
    {
      get { return _itemDropChance; }
      set { _itemDropChance = value; }
    }

    private int _minGold = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"minGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minGold
    {
      get { return _minGold; }
      set { _minGold = value; }
    }

    private int _maxGold = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maxGold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxGold
    {
      get { return _maxGold; }
      set { _maxGold = value; }
    }

    private int _minTonic = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"minTonic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minTonic
    {
      get { return _minTonic; }
      set { _minTonic = value; }
    }

    private int _maxTonic = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"maxTonic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxTonic
    {
      get { return _maxTonic; }
      set { _maxTonic = value; }
    }

    private bool _isBoss = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"isBoss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBoss
    {
      get { return _isBoss; }
      set { _isBoss = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}