//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MonsterType.proto
namespace com.lvl6.aoc2.proto
{
    [global::ProtoBuf.ProtoContract(Name=@"MonsterType")]
    public enum MonsterType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOBLIN", Value=0)]
      GOBLIN = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TROLL", Value=1)]
      TROLL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRAGON", Value=2)]
      DRAGON = 2
    }
  
}