//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MonsterType.proto
namespace com.lvl6.aoc2.proto
{
    [global::ProtoBuf.ProtoContract(Name=@"MonsterType")]
    public enum MonsterType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ROCK_KING", Value=1)]
      ROCK_KING = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKELETON", Value=2)]
      SKELETON = 2
    }
  
}