//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RarityType.proto
namespace com.lvl6.aoc2.proto
{
    [global::ProtoBuf.ProtoContract(Name=@"RarityType")]
    public enum RarityType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMON", Value=0)]
      COMMON = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNCOMMON", Value=1)]
      UNCOMMON = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RARE", Value=2)]
      RARE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUPER_RARE", Value=3)]
      SUPER_RARE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LEGENDARY", Value=4)]
      LEGENDARY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EPIC", Value=5)]
      EPIC = 5
    }
  
}