//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ResourceType.proto
namespace com.lvl6.aoc2.proto
{
    [global::ProtoBuf.ProtoContract(Name=@"ResourceType")]
    public enum ResourceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD", Value=0)]
      GOLD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TONIC", Value=1)]
      TONIC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GEMS", Value=2)]
      GEMS = 2
    }
  
}