//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserEquipmentProto.proto
namespace com.lvl6.aoc2.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserEquipmentProto")]
  public partial class UserEquipmentProto : global::ProtoBuf.IExtensible
  {
    public UserEquipmentProto() {}
    

    private int _userID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userID
    {
      get { return _userID; }
      set { _userID = value; }
    }

    private int _equipID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"equipID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipID
    {
      get { return _equipID; }
      set { _equipID = value; }
    }

    private int _equipLevel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"equipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipLevel
    {
      get { return _equipLevel; }
      set { _equipLevel = value; }
    }

    private int _currDurability = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"currDurability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int currDurability
    {
      get { return _currDurability; }
      set { _currDurability = value; }
    }

    private bool _equipped = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"equipped", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool equipped
    {
      get { return _equipped; }
      set { _equipped = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}