//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Info.proto
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FullUserStructureProto")]
  public partial class FullUserStructureProto : global::ProtoBuf.IExtensible
  {
    public FullUserStructureProto() {}
    

    private int _userStructId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userStructId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userStructId
    {
      get { return _userStructId; }
      set { _userStructId = value; }
    }

    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }

    private int _structId = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"structId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structId
    {
      get { return _structId; }
      set { _structId = value; }
    }

    private com.lvl6.proto.StructType _structType = com.lvl6.proto.StructType.TOWN_HALL;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"structType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(com.lvl6.proto.StructType.TOWN_HALL)]
    public com.lvl6.proto.StructType structType
    {
      get { return _structType; }
      set { _structType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"StructType")]
    public enum StructType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOWN_HALL", Value=0)]
      TOWN_HALL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_COLLECTOR", Value=1)]
      GOLD_COLLECTOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GOLD_STORAGE", Value=2)]
      GOLD_STORAGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TONIC_COLLECTOR", Value=3)]
      TONIC_COLLECTOR = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TONIC_STORAGE", Value=4)]
      TONIC_STORAGE = 4
    }