//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AocTwoEventProtocol.proto
namespace proto
{
    [global::ProtoBuf.ProtoContract(Name=@"AocTwoEventProtocolRequest")]
    public enum AocTwoEventProtocolRequest
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_TRAIN_OR_UPGRADE_SPELL_EVENT", Value=0)]
      C_TRAIN_OR_UPGRADE_SPELL_EVENT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_BUILD_OR_UPGRADE_STRUCTURE_EVENT", Value=1)]
      C_BUILD_OR_UPGRADE_STRUCTURE_EVENT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_REFILL_HP_OR_MANA_WITH_CONSUMABLE_EVENT", Value=2)]
      C_REFILL_HP_OR_MANA_WITH_CONSUMABLE_EVENT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_REPAIR_EQUIP_EVENT", Value=3)]
      C_REPAIR_EQUIP_EVENT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_SELECT_USER_CLASS_TYPE_EVENT", Value=4)]
      C_SELECT_USER_CLASS_TYPE_EVENT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_STARTUP_EVENT", Value=5)]
      C_STARTUP_EVENT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_RETURN_HOME_EVENT", Value=6)]
      C_RETURN_HOME_EVENT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"C_COMPLETE_DUNGEON_EVENT", Value=7)]
      C_COMPLETE_DUNGEON_EVENT = 7
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"AocTwoEventProtocolResponse")]
    public enum AocTwoEventProtocolResponse
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_TRAIN_OR_UPGRADE_SPELL_EVENT", Value=0)]
      S_TRAIN_OR_UPGRADE_SPELL_EVENT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_BUILD_OR_UPGRADE_STRUCTURE_EVENT", Value=1)]
      S_BUILD_OR_UPGRADE_STRUCTURE_EVENT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_REFILL_HP_OR_MANA_WITH_CONSUMABLE_EVENT", Value=2)]
      S_REFILL_HP_OR_MANA_WITH_CONSUMABLE_EVENT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_REPAIR_EQUIP_EVENT", Value=3)]
      S_REPAIR_EQUIP_EVENT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_SELECT_USER_CLASS_TYPE_EVENT", Value=4)]
      S_SELECT_USER_CLASS_TYPE_EVENT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_STARTUP_EVENT", Value=5)]
      S_STARTUP_EVENT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_RETURN_HOME_EVENT", Value=6)]
      S_RETURN_HOME_EVENT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_COMPLETE_DUNGEON_EVENT", Value=7)]
      S_COMPLETE_DUNGEON_EVENT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"S_FORCE_LOGOUT_EVENT", Value=100)]
      S_FORCE_LOGOUT_EVENT = 100
    }
  
}