//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BuildOrUpgradeSpellEvent.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildOrUpgradeSpellRequestProto")]
  public partial class BuildOrUpgradeSpellRequestProto : global::ProtoBuf.IExtensible
  {
    public BuildOrUpgradeSpellRequestProto() {}
    

    private string _spellId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"spellId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string spellId
    {
      get { return _spellId; }
      set { _spellId = value; }
    }

    private int _slotNum = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"slotNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int slotNum
    {
      get { return _slotNum; }
      set { _slotNum = value; }
    }

    private bool _speedUp = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"speedUp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool speedUp
    {
      get { return _speedUp; }
      set { _speedUp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildOrUpgradeSpellResponseProto")]
  public partial class BuildOrUpgradeSpellResponseProto : global::ProtoBuf.IExtensible
  {
    public BuildOrUpgradeSpellResponseProto() {}
    

    private proto.BuildOrUpgradeSpellResponseProto.BuildOrUpgradeSpellStatus _status = proto.BuildOrUpgradeSpellResponseProto.BuildOrUpgradeSpellStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.BuildOrUpgradeSpellResponseProto.BuildOrUpgradeSpellStatus.SUCCESS)]
    public proto.BuildOrUpgradeSpellResponseProto.BuildOrUpgradeSpellStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"BuildOrUpgradeSpellStatus")]
    public enum BuildOrUpgradeSpellStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_INSUFFICIENT_RESOURCE", Value=1)]
      FAIL_INSUFFICIENT_RESOURCE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_SLOT_IN_USE", Value=2)]
      FAIL_SLOT_IN_USE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_WRONG_CLASS_TYPE_FOR_SPELL", Value=3)]
      FAIL_WRONG_CLASS_TYPE_FOR_SPELL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_TOO_LOW_LEVEL_FOR_SPELL", Value=4)]
      FAIL_TOO_LOW_LEVEL_FOR_SPELL = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=5)]
      FAIL_OTHER = 5
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}