//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BuildConsumableEvent.proto
// Note: requires additional types generated from: FullUserProto.proto
// Note: requires additional types generated from: UserConsumableQueueProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildConsumableRequestProto")]
  public partial class BuildConsumableRequestProto : global::ProtoBuf.IExtensible
  {
    public BuildConsumableRequestProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.UserConsumableQueueProto> _ucqDelete = new global::System.Collections.Generic.List<proto.UserConsumableQueueProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ucqDelete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.UserConsumableQueueProto> ucqDelete
    {
      get { return _ucqDelete; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.UserConsumableQueueProto> _ucqUpdate = new global::System.Collections.Generic.List<proto.UserConsumableQueueProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"ucqUpdate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.UserConsumableQueueProto> ucqUpdate
    {
      get { return _ucqUpdate; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.UserConsumableQueueProto> _ucqNew = new global::System.Collections.Generic.List<proto.UserConsumableQueueProto>();
    [global::ProtoBuf.ProtoMember(4, Name=@"ucqNew", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.UserConsumableQueueProto> ucqNew
    {
      get { return _ucqNew; }
    }
  

    private bool _usingGems = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"usingGems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool usingGems
    {
      get { return _usingGems; }
      set { _usingGems = value; }
    }

    private long _clientTimeMillis = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"clientTimeMillis", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long clientTimeMillis
    {
      get { return _clientTimeMillis; }
      set { _clientTimeMillis = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BuildConsumableResponseProto")]
  public partial class BuildConsumableResponseProto : global::ProtoBuf.IExtensible
  {
    public BuildConsumableResponseProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private proto.BuildConsumableResponseProto.BuildConsumableStatus _status = proto.BuildConsumableResponseProto.BuildConsumableStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.BuildConsumableResponseProto.BuildConsumableStatus.SUCCESS)]
    public proto.BuildConsumableResponseProto.BuildConsumableStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"BuildConsumableStatus")]
    public enum BuildConsumableStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_UNSYNCHRONIZED_TIMES", Value=1)]
      FAIL_UNSYNCHRONIZED_TIMES = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NOT_ENOUGH_TONIC", Value=2)]
      FAIL_NOT_ENOUGH_TONIC = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=3)]
      FAIL_OTHER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}