//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChestProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChestProto")]
  public partial class ChestProto : global::ProtoBuf.IExtensible
  {
    public ChestProto() {}
    

    private string _chestID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chestID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string chestID
    {
      get { return _chestID; }
      set { _chestID = value; }
    }

    private string _equipID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"equipID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string equipID
    {
      get { return _equipID; }
      set { _equipID = value; }
    }

    private int _equipChance = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"equipChance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipChance
    {
      get { return _equipChance; }
      set { _equipChance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Chests")]
    public enum Chests
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIRST_RELEASED_CHEST", Value=1)]
      FIRST_RELEASED_CHEST = 1
    }
  
}