//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ClassType.proto
namespace proto
{
    [global::ProtoBuf.ProtoContract(Name=@"ClassType")]
    public enum ClassType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WARRIOR", Value=0)]
      WARRIOR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARCHER", Value=1)]
      ARCHER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WIZARD", Value=2)]
      WIZARD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ALL", Value=3)]
      ALL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NOOB", Value=4)]
      NOOB = 4
    }
  
}