//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: CompleteDungeonEvent.proto
// Note: requires additional types generated from: ItemProto.proto
// Note: requires additional types generated from: FullUserProto.proto
// Note: requires additional types generated from: EquipmentProto.proto
// Note: requires additional types generated from: ChestProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompleteDungeonRequestProto")]
  public partial class CompleteDungeonRequestProto : global::ProtoBuf.IExtensible
  {
    public CompleteDungeonRequestProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.ChestProto> _chestGained = new global::System.Collections.Generic.List<proto.ChestProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"chestGained", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.ChestProto> chestGained
    {
      get { return _chestGained; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.EquipmentProto> _equipsGained = new global::System.Collections.Generic.List<proto.EquipmentProto>();
    [global::ProtoBuf.ProtoMember(3, Name=@"equipsGained", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.EquipmentProto> equipsGained
    {
      get { return _equipsGained; }
    }
  
    private readonly global::System.Collections.Generic.List<proto.ItemProto> _itemsGained = new global::System.Collections.Generic.List<proto.ItemProto>();
    [global::ProtoBuf.ProtoMember(4, Name=@"itemsGained", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.ItemProto> itemsGained
    {
      get { return _itemsGained; }
    }
  

    private string _dungeonRoomName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dungeonRoomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dungeonRoomName
    {
      get { return _dungeonRoomName; }
      set { _dungeonRoomName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CompleteDungeonResponseProto")]
  public partial class CompleteDungeonResponseProto : global::ProtoBuf.IExtensible
  {
    public CompleteDungeonResponseProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private proto.CompleteDungeonResponseProto.CompleteDungeonStatus _status = proto.CompleteDungeonResponseProto.CompleteDungeonStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.CompleteDungeonResponseProto.CompleteDungeonStatus.SUCCESS)]
    public proto.CompleteDungeonResponseProto.CompleteDungeonStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"CompleteDungeonStatus")]
    public enum CompleteDungeonStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_CHEST_OR_EQUIPS_DONT_EXIST", Value=1)]
      FAIL_CHEST_OR_EQUIPS_DONT_EXIST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=2)]
      FAIL_OTHER = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}