//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: FunctionalityType.proto
namespace proto
{
    [global::ProtoBuf.ProtoContract(Name=@"FunctionalityType")]
    public enum FunctionalityType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESOURCE_COLLECTOR", Value=0)]
      RESOURCE_COLLECTOR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESOURCE_STORAGE", Value=1)]
      RESOURCE_STORAGE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIBRARY", Value=2)]
      LIBRARY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLACKSMITH", Value=3)]
      BLACKSMITH = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STORAGE", Value=4)]
      STORAGE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WIZARD", Value=5)]
      WIZARD = 5
    }
  
}