//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ItemProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemProto")]
  public partial class ItemProto : global::ProtoBuf.IExtensible
  {
    public ItemProto() {}
    

    private string _itemID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string itemID
    {
      get { return _itemID; }
      set { _itemID = value; }
    }

    private int _itemType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemType
    {
      get { return _itemType; }
      set { _itemType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"itemType")]
    public enum itemType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"QUEST_ITEMS", Value=0)]
      QUEST_ITEMS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIRST_RELEASED_KEY", Value=1)]
      FIRST_RELEASED_KEY = 1
    }
  
}