//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LevelUpEvent.proto
// Note: requires additional types generated from: FullUserProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LevelUpRequestProto")]
  public partial class LevelUpRequestProto : global::ProtoBuf.IExtensible
  {
    public LevelUpRequestProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LevelUpResponseProto")]
  public partial class LevelUpResponseProto : global::ProtoBuf.IExtensible
  {
    public LevelUpResponseProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private proto.LevelUpResponseProto.LevelUpStatus _status = proto.LevelUpResponseProto.LevelUpStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.LevelUpResponseProto.LevelUpStatus.SUCCESS)]
    public proto.LevelUpResponseProto.LevelUpStatus status
    {
      get { return _status; }
      set { _status = value; }
    }

    private int _newLevel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"newLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int newLevel
    {
      get { return _newLevel; }
      set { _newLevel = value; }
    }

    private int _newNextLevel = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"newNextLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int newNextLevel
    {
      get { return _newNextLevel; }
      set { _newNextLevel = value; }
    }

    private int _experienceRequiredForNewNextLevel = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"experienceRequiredForNewNextLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int experienceRequiredForNewNextLevel
    {
      get { return _experienceRequiredForNewNextLevel; }
      set { _experienceRequiredForNewNextLevel = value; }
    }

    private int _newHp = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"newHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int newHp
    {
      get { return _newHp; }
      set { _newHp = value; }
    }

    private int _newMana = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"newMana", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int newMana
    {
      get { return _newMana; }
      set { _newMana = value; }
    }

    private int _newAttack = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"newAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int newAttack
    {
      get { return _newAttack; }
      set { _newAttack = value; }
    }

    private int _newDefense = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"newDefense", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int newDefense
    {
      get { return _newDefense; }
      set { _newDefense = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LevelUpStatus")]
    public enum LevelUpStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NOT_ENOUGH_EXP", Value=1)]
      FAIL_NOT_ENOUGH_EXP = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_ALREADY_AT_MAX_LEVEL", Value=2)]
      FAIL_ALREADY_AT_MAX_LEVEL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=3)]
      FAIL_OTHER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}