//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MonsterProto.proto
// Note: requires additional types generated from: MonsterType.proto
// Note: requires additional types generated from: ColorProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterProto")]
  public partial class MonsterProto : global::ProtoBuf.IExtensible
  {
    public MonsterProto() {}
    

    private int _monsterID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"monsterID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monsterID
    {
      get { return _monsterID; }
      set { _monsterID = value; }
    }

    private int _maxHealth = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"maxHealth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxHealth
    {
      get { return _maxHealth; }
      set { _maxHealth = value; }
    }

    private int _maxMana = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxMana", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxMana
    {
      get { return _maxMana; }
      set { _maxMana = value; }
    }

    private int _attack = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"attack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attack
    {
      get { return _attack; }
      set { _attack = value; }
    }

    private int _defense = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"defense", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int defense
    {
      get { return _defense; }
      set { _defense = value; }
    }
    private proto.MonsterType _type;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.MonsterType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private proto.ColorProto _color = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.ColorProto color
    {
      get { return _color; }
      set { _color = value; }
    }

    private float _size = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float size
    {
      get { return _size; }
      set { _size = value; }
    }

    private int _experience = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"experience", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int experience
    {
      get { return _experience; }
      set { _experience = value; }
    }

    private bool _isBoss = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"isBoss", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBoss
    {
      get { return _isBoss; }
      set { _isBoss = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}