//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PurchaseGoldOrTonicEvent.proto
// Note: requires additional types generated from: FullUserProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PurchaseGoldOrTonicRequestProto")]
  public partial class PurchaseGoldOrTonicRequestProto : global::ProtoBuf.IExtensible
  {
    public PurchaseGoldOrTonicRequestProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private bool _isGold = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isGold", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isGold
    {
      get { return _isGold; }
      set { _isGold = value; }
    }

    private int _purchaseType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"purchaseType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int purchaseType
    {
      get { return _purchaseType; }
      set { _purchaseType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PurchaseGoldOrTonicResponseProto")]
  public partial class PurchaseGoldOrTonicResponseProto : global::ProtoBuf.IExtensible
  {
    public PurchaseGoldOrTonicResponseProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private proto.PurchaseGoldOrTonicResponseProto.PurchaseGoldOrTonicStatus _status = proto.PurchaseGoldOrTonicResponseProto.PurchaseGoldOrTonicStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.PurchaseGoldOrTonicResponseProto.PurchaseGoldOrTonicStatus.SUCCESS)]
    public proto.PurchaseGoldOrTonicResponseProto.PurchaseGoldOrTonicStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"PurchaseGoldOrTonicStatus")]
    public enum PurchaseGoldOrTonicStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NOT_ENOUGH_GEMS", Value=1)]
      FAIL_NOT_ENOUGH_GEMS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_ALREADY_MAX_RESOURCE", Value=2)]
      FAIL_ALREADY_MAX_RESOURCE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=3)]
      FAIL_OTHER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"PurchaseType")]
    public enum PurchaseType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TEN_PERCENT", Value=1)]
      TEN_PERCENT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FIFTY_PERCENT", Value=2)]
      FIFTY_PERCENT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HUNDRED_PERCENT", Value=3)]
      HUNDRED_PERCENT = 3
    }
  
}