//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RoomRewardProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomRewardProto")]
  public partial class RoomRewardProto : global::ProtoBuf.IExtensible
  {
    public RoomRewardProto() {}
    

    private int _dungeonID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeonID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dungeonID
    {
      get { return _dungeonID; }
      set { _dungeonID = value; }
    }

    private int _roomID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomID
    {
      get { return _roomID; }
      set { _roomID = value; }
    }

    private int _chestID = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"chestID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chestID
    {
      get { return _chestID; }
      set { _chestID = value; }
    }

    private int _chestDropChance = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chestDropChance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chestDropChance
    {
      get { return _chestDropChance; }
      set { _chestDropChance = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _equipIDs = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(5, Name=@"equipIDs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> equipIDs
    {
      get { return _equipIDs; }
    }
  

    private int _equipDropChance = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"equipDropChance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipDropChance
    {
      get { return _equipDropChance; }
      set { _equipDropChance = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}