//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SelectUserClassTypeEvent.proto
// Note: requires additional types generated from: ClassType.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectUserClassTypeRequestProto")]
  public partial class SelectUserClassTypeRequestProto : global::ProtoBuf.IExtensible
  {
    public SelectUserClassTypeRequestProto() {}
    

    private proto.ClassType _classType = proto.ClassType.ALL;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"classType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.ClassType.ALL)]
    public proto.ClassType classType
    {
      get { return _classType; }
      set { _classType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectUserClassTypeResponseProto")]
  public partial class SelectUserClassTypeResponseProto : global::ProtoBuf.IExtensible
  {
    public SelectUserClassTypeResponseProto() {}
    

    private proto.SelectUserClassTypeResponseProto.SelectUserClassTypeStatus _status = proto.SelectUserClassTypeResponseProto.SelectUserClassTypeStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.SelectUserClassTypeResponseProto.SelectUserClassTypeStatus.SUCCESS)]
    public proto.SelectUserClassTypeResponseProto.SelectUserClassTypeStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SelectUserClassTypeStatus")]
    public enum SelectUserClassTypeStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_WRONG_CLASS_TYPE", Value=1)]
      FAIL_WRONG_CLASS_TYPE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_TOO_LOW_LEVEL", Value=2)]
      FAIL_TOO_LOW_LEVEL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=3)]
      FAIL_OTHER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}