//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SpeedUpBuildUserConsumableEvent.proto
// Note: requires additional types generated from: UserConsumableQueueProto.proto
// Note: requires additional types generated from: FullUserProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpeedUpBuildUserConsumableRequestProto")]
  public partial class SpeedUpBuildUserConsumableRequestProto : global::ProtoBuf.IExtensible
  {
    public SpeedUpBuildUserConsumableRequestProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.UserConsumableQueueProto> _queuedConsumables = new global::System.Collections.Generic.List<proto.UserConsumableQueueProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"queuedConsumables", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.UserConsumableQueueProto> queuedConsumables
    {
      get { return _queuedConsumables; }
    }
  

    private int _minutesRemaining = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"minutesRemaining", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minutesRemaining
    {
      get { return _minutesRemaining; }
      set { _minutesRemaining = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpeedUpBuildUserConsumableResponseProto")]
  public partial class SpeedUpBuildUserConsumableResponseProto : global::ProtoBuf.IExtensible
  {
    public SpeedUpBuildUserConsumableResponseProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private proto.SpeedUpBuildUserConsumableResponseProto.SpeedUpBuildUserConsumableStatus _status = proto.SpeedUpBuildUserConsumableResponseProto.SpeedUpBuildUserConsumableStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.SpeedUpBuildUserConsumableResponseProto.SpeedUpBuildUserConsumableStatus.SUCCESS)]
    public proto.SpeedUpBuildUserConsumableResponseProto.SpeedUpBuildUserConsumableStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SpeedUpBuildUserConsumableStatus")]
    public enum SpeedUpBuildUserConsumableStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NOT_ENOUGH_GEMS", Value=1)]
      FAIL_NOT_ENOUGH_GEMS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_QUEUE_TIME_IS_ZERO", Value=2)]
      FAIL_QUEUE_TIME_IS_ZERO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=3)]
      FAIL_OTHER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}