//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SpeedUpTrainOrUpgradeSpellEvent.proto
// Note: requires additional types generated from: FullUserProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpeedUpTrainOrUpgradeSpellRequestProto")]
  public partial class SpeedUpTrainOrUpgradeSpellRequestProto : global::ProtoBuf.IExtensible
  {
    public SpeedUpTrainOrUpgradeSpellRequestProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private string _spellId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"spellId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string spellId
    {
      get { return _spellId; }
      set { _spellId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpeedUpTrainOrUpgradeSpellResponseProto")]
  public partial class SpeedUpTrainOrUpgradeSpellResponseProto : global::ProtoBuf.IExtensible
  {
    public SpeedUpTrainOrUpgradeSpellResponseProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private proto.SpeedUpTrainOrUpgradeSpellResponseProto.SpeedUpTrainOrUpgradeSpellStatus _status = proto.SpeedUpTrainOrUpgradeSpellResponseProto.SpeedUpTrainOrUpgradeSpellStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.SpeedUpTrainOrUpgradeSpellResponseProto.SpeedUpTrainOrUpgradeSpellStatus.SUCCESS)]
    public proto.SpeedUpTrainOrUpgradeSpellResponseProto.SpeedUpTrainOrUpgradeSpellStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SpeedUpTrainOrUpgradeSpellStatus")]
    public enum SpeedUpTrainOrUpgradeSpellStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NOT_ENOUGH_GEMS", Value=1)]
      FAIL_NOT_ENOUGH_GEMS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=9)]
      FAIL_OTHER = 9
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}