//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SpeedUpRepairEquipEvent.proto
// Note: requires additional types generated from: UserEquipRepairProto.proto
// Note: requires additional types generated from: FullUserProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpeedUpRepairEquipRequestProto")]
  public partial class SpeedUpRepairEquipRequestProto : global::ProtoBuf.IExtensible
  {
    public SpeedUpRepairEquipRequestProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }
    private readonly global::System.Collections.Generic.List<proto.UserEquipRepairProto> _equipsInQueue = new global::System.Collections.Generic.List<proto.UserEquipRepairProto>();
    [global::ProtoBuf.ProtoMember(2, Name=@"equipsInQueue", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<proto.UserEquipRepairProto> equipsInQueue
    {
      get { return _equipsInQueue; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpeedUpRepairEquipResponseProto")]
  public partial class SpeedUpRepairEquipResponseProto : global::ProtoBuf.IExtensible
  {
    public SpeedUpRepairEquipResponseProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private proto.SpeedUpRepairEquipResponseProto.SpeedUpRepairEquipStatus _status = proto.SpeedUpRepairEquipResponseProto.SpeedUpRepairEquipStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.SpeedUpRepairEquipResponseProto.SpeedUpRepairEquipStatus.SUCCESS)]
    public proto.SpeedUpRepairEquipResponseProto.SpeedUpRepairEquipStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SpeedUpRepairEquipStatus")]
    public enum SpeedUpRepairEquipStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NOT_ENOUGH_GEMS", Value=1)]
      FAIL_NOT_ENOUGH_GEMS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_QUEUE_TIME_IS_ZERO", Value=2)]
      FAIL_QUEUE_TIME_IS_ZERO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=3)]
      FAIL_OTHER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}