//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SpeedUpBuildOrUpgradeStructureEvent.proto
// Note: requires additional types generated from: FullUserProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpeedUpBuildOrUpgradeStructureRequestProto")]
  public partial class SpeedUpBuildOrUpgradeStructureRequestProto : global::ProtoBuf.IExtensible
  {
    public SpeedUpBuildOrUpgradeStructureRequestProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private string _userStructureId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userStructureId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userStructureId
    {
      get { return _userStructureId; }
      set { _userStructureId = value; }
    }

    private bool _isBuild = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"isBuild", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isBuild
    {
      get { return _isBuild; }
      set { _isBuild = value; }
    }

    private int _minutesRemaining = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"minutesRemaining", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minutesRemaining
    {
      get { return _minutesRemaining; }
      set { _minutesRemaining = value; }
    }

    private bool _finishedConstructing = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"finishedConstructing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool finishedConstructing
    {
      get { return _finishedConstructing; }
      set { _finishedConstructing = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpeedUpBuildOrUpgradeStructureResponseProto")]
  public partial class SpeedUpBuildOrUpgradeStructureResponseProto : global::ProtoBuf.IExtensible
  {
    public SpeedUpBuildOrUpgradeStructureResponseProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private bool _finishedConstructing = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"finishedConstructing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool finishedConstructing
    {
      get { return _finishedConstructing; }
      set { _finishedConstructing = value; }
    }

    private proto.SpeedUpBuildOrUpgradeStructureResponseProto.SpeedUpBuildOrUpgradeStructureStatus _status = proto.SpeedUpBuildOrUpgradeStructureResponseProto.SpeedUpBuildOrUpgradeStructureStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.SpeedUpBuildOrUpgradeStructureResponseProto.SpeedUpBuildOrUpgradeStructureStatus.SUCCESS)]
    public proto.SpeedUpBuildOrUpgradeStructureResponseProto.SpeedUpBuildOrUpgradeStructureStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SpeedUpBuildOrUpgradeStructureStatus")]
    public enum SpeedUpBuildOrUpgradeStructureStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NOT_ENOUGH_GEMS", Value=1)]
      FAIL_NOT_ENOUGH_GEMS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_QUEUE_TIME_IS_ZERO", Value=2)]
      FAIL_QUEUE_TIME_IS_ZERO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=3)]
      FAIL_OTHER = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}