//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SpellFunctionType.proto
namespace proto
{
    [global::ProtoBuf.ProtoContract(Name=@"SpellFunctionType")]
    public enum SpellFunctionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK", Value=0)]
      ATTACK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUFF", Value=1)]
      BUFF = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEAL", Value=2)]
      HEAL = 2
    }
  
}