//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SpellProto.proto
// Note: requires additional types generated from: ClassType.proto
// Note: requires additional types generated from: ResourceType.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpellProto")]
  public partial class SpellProto : global::ProtoBuf.IExtensible
  {
    public SpellProto() {}
    

    private int _spellID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"spellID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int spellID
    {
      get { return _spellID; }
      set { _spellID = value; }
    }
    private proto.ClassType _classType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"classType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.ClassType classType
    {
      get { return _classType; }
      set { _classType = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private proto.SpellProto.SpellFunctionType _function = proto.SpellProto.SpellFunctionType.ATTACK;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"function", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.SpellProto.SpellFunctionType.ATTACK)]
    public proto.SpellProto.SpellFunctionType function
    {
      get { return _function; }
      set { _function = value; }
    }

    private proto.SpellProto.SpellTargetType _targetType = proto.SpellProto.SpellTargetType.PERSONAL;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"targetType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.SpellProto.SpellTargetType.PERSONAL)]
    public proto.SpellProto.SpellTargetType targetType
    {
      get { return _targetType; }
      set { _targetType = value; }
    }

    private proto.SpellProto.SpellDirectionType _directionType = proto.SpellProto.SpellDirectionType.STRAIGHT;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"directionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.SpellProto.SpellDirectionType.STRAIGHT)]
    public proto.SpellProto.SpellDirectionType directionType
    {
      get { return _directionType; }
      set { _directionType = value; }
    }

    private float _strength = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float strength
    {
      get { return _strength; }
      set { _strength = value; }
    }

    private float _force = (float)1;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"force", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float force
    {
      get { return _force; }
      set { _force = value; }
    }

    private int _manaCost = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"manaCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int manaCost
    {
      get { return _manaCost; }
      set { _manaCost = value; }
    }

    private float _deliveryDuration = default(float);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"deliveryDuration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float deliveryDuration
    {
      get { return _deliveryDuration; }
      set { _deliveryDuration = value; }
    }

    private int _numberParticles = (int)1;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"numberParticles", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)1)]
    public int numberParticles
    {
      get { return _numberParticles; }
      set { _numberParticles = value; }
    }

    private float _particleSpeed = default(float);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"particleSpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float particleSpeed
    {
      get { return _particleSpeed; }
      set { _particleSpeed = value; }
    }

    private float _particleDuration = (float)0.1;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"particleDuration", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)0.1)]
    public float particleDuration
    {
      get { return _particleDuration; }
      set { _particleDuration = value; }
    }

    private int _hitsPerParticle = default(int);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"hitsPerParticle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int hitsPerParticle
    {
      get { return _hitsPerParticle; }
      set { _hitsPerParticle = value; }
    }

    private float _deliverySpeed = default(float);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"deliverySpeed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float deliverySpeed
    {
      get { return _deliverySpeed; }
      set { _deliverySpeed = value; }
    }

    private bool _targetted = (bool)false;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"targetted", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue((bool)false)]
    public bool targetted
    {
      get { return _targetted; }
      set { _targetted = value; }
    }

    private float _size = (float)1;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue((float)1)]
    public float size
    {
      get { return _size; }
      set { _size = value; }
    }

    private float _castTime = default(float);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"castTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float castTime
    {
      get { return _castTime; }
      set { _castTime = value; }
    }

    private float _coolDown = default(float);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"coolDown", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float coolDown
    {
      get { return _coolDown; }
      set { _coolDown = value; }
    }

    private float _retargetTime = default(float);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"retargetTime", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float retargetTime
    {
      get { return _retargetTime; }
      set { _retargetTime = value; }
    }

    private float _range = default(float);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"range", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float range
    {
      get { return _range; }
      set { _range = value; }
    }

    private float _angle = default(float);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"angle", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float angle
    {
      get { return _angle; }
      set { _angle = value; }
    }

    private float _area = default(float);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"area", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float area
    {
      get { return _area; }
      set { _area = value; }
    }

    private int _levelReq = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"levelReq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int levelReq
    {
      get { return _levelReq; }
      set { _levelReq = value; }
    }

    private int _spellLvl = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"spellLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int spellLvl
    {
      get { return _spellLvl; }
      set { _spellLvl = value; }
    }

    private int _researchCost = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"researchCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int researchCost
    {
      get { return _researchCost; }
      set { _researchCost = value; }
    }

    private int _researchTime = default(int);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"researchTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int researchTime
    {
      get { return _researchTime; }
      set { _researchTime = value; }
    }
    private proto.ResourceType _researchResource;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"researchResource", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.ResourceType researchResource
    {
      get { return _researchResource; }
      set { _researchResource = value; }
    }

    private proto.SpellProto.SpellParticleType _particleType = proto.SpellProto.SpellParticleType.SPHERE;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"particleType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.SpellProto.SpellParticleType.SPHERE)]
    public proto.SpellProto.SpellParticleType particleType
    {
      get { return _particleType; }
      set { _particleType = value; }
    }

    private proto.SpellProto.UnitStat _stat = proto.SpellProto.UnitStat.STRENGTH;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"stat", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.SpellProto.UnitStat.STRENGTH)]
    public proto.SpellProto.UnitStat stat
    {
      get { return _stat; }
      set { _stat = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"SpellFunctionType")]
    public enum SpellFunctionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK", Value=0)]
      ATTACK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BUFF", Value=1)]
      BUFF = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEAL", Value=2)]
      HEAL = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SpellTargetType")]
    public enum SpellTargetType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SELF", Value=0)]
      SELF = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PERSONAL", Value=1)]
      PERSONAL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TARGETTED", Value=2)]
      TARGETTED = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SpellDirectionType")]
    public enum SpellDirectionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRAIGHT", Value=0)]
      STRAIGHT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ARC", Value=1)]
      ARC = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCATTERED", Value=2)]
      SCATTERED = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"SpellParticleType")]
    public enum SpellParticleType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SPHERE", Value=0)]
      SPHERE = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIGHTNING", Value=1)]
      LIGHTNING = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STARFALL", Value=2)]
      STARFALL = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SHOCK", Value=3)]
      SHOCK = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DUST", Value=4)]
      DUST = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ICICLE", Value=5)]
      ICICLE = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUTURE1", Value=6)]
      FUTURE1 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUTURE2", Value=7)]
      FUTURE2 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUTURE3", Value=8)]
      FUTURE3 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUTURE4", Value=9)]
      FUTURE4 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUTURE5", Value=10)]
      FUTURE5 = 10
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"UnitStat")]
    public enum UnitStat
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STRENGTH", Value=0)]
      STRENGTH = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DEFENSE", Value=1)]
      DEFENSE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESISTANCE", Value=2)]
      RESISTANCE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MOVE_SPEED", Value=3)]
      MOVE_SPEED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ATTACK_SPEED", Value=4)]
      ATTACK_SPEED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MANA", Value=5)]
      MANA = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEALTH", Value=6)]
      HEALTH = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}