//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StartupEvent.proto
// Note: requires additional types generated from: FullUserProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartupRequestProto")]
  public partial class StartupRequestProto : global::ProtoBuf.IExtensible
  {
    public StartupRequestProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private proto.StartupRequestProto.LoginType _loginType = proto.StartupRequestProto.LoginType.GAME_CENTER_ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"loginType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.StartupRequestProto.LoginType.GAME_CENTER_ID)]
    public proto.StartupRequestProto.LoginType loginType
    {
      get { return _loginType; }
      set { _loginType = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"LoginType")]
    public enum LoginType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_CENTER_ID", Value=0)]
      GAME_CENTER_ID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UDID", Value=1)]
      UDID = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartupResponseProto")]
  public partial class StartupResponseProto : global::ProtoBuf.IExtensible
  {
    public StartupResponseProto() {}
    

    private proto.FullUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.FullUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private long _currentServerTime = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"currentServerTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long currentServerTime
    {
      get { return _currentServerTime; }
      set { _currentServerTime = value; }
    }

    private proto.StartupResponseProto.StartupStatus _status = proto.StartupResponseProto.StartupStatus.SUCCESS_GAME_CENTER_ID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.StartupResponseProto.StartupStatus.SUCCESS_GAME_CENTER_ID)]
    public proto.StartupResponseProto.StartupStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"StartupStatus")]
    public enum StartupStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS_GAME_CENTER_ID", Value=0)]
      SUCCESS_GAME_CENTER_ID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS_UDID", Value=1)]
      SUCCESS_UDID = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS_NEW_USER", Value=2)]
      SUCCESS_NEW_USER = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=4)]
      FAIL_OTHER = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}