//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: StructProto.proto
// Note: requires additional types generated from: ResourceType.proto
// Note: requires additional types generated from: CoordinateProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StructureProto")]
  public partial class StructureProto : global::ProtoBuf.IExtensible
  {
    public StructureProto() {}
    

    private string _id = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }

    private int _structureID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"structureID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structureID
    {
      get { return _structureID; }
      set { _structureID = value; }
    }

    private proto.StructureProto.StructureFunction _function = proto.StructureProto.StructureFunction.TOWN_HALL;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"function", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.StructureProto.StructureFunction.TOWN_HALL)]
    public proto.StructureProto.StructureFunction function
    {
      get { return _function; }
      set { _function = value; }
    }

    private int _buildCost = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"buildCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buildCost
    {
      get { return _buildCost; }
      set { _buildCost = value; }
    }

    private int _buildTime = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buildTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buildTime
    {
      get { return _buildTime; }
      set { _buildTime = value; }
    }
    private proto.ResourceType _buildResource;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"buildResource", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.ResourceType buildResource
    {
      get { return _buildResource; }
      set { _buildResource = value; }
    }

    private int _upgradeTownHallLevel = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"upgradeTownHallLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int upgradeTownHallLevel
    {
      get { return _upgradeTownHallLevel; }
      set { _upgradeTownHallLevel = value; }
    }

    private proto.CoordinateProto _size = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.CoordinateProto size
    {
      get { return _size; }
      set { _size = value; }
    }

    private int _buildSpeedUpBaseCost = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"buildSpeedUpBaseCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buildSpeedUpBaseCost
    {
      get { return _buildSpeedUpBaseCost; }
      set { _buildSpeedUpBaseCost = value; }
    }

    private int _functionValue = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"functionValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int functionValue
    {
      get { return _functionValue; }
      set { _functionValue = value; }
    }
    private proto.ResourceType _functionResource;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"functionResource", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public proto.ResourceType functionResource
    {
      get { return _functionResource; }
      set { _functionResource = value; }
    }

    private int _speedUpFunctionBaseCost = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"speedUpFunctionBaseCost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int speedUpFunctionBaseCost
    {
      get { return _speedUpFunctionBaseCost; }
      set { _speedUpFunctionBaseCost = value; }
    }

    private int _capacity = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"capacity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int capacity
    {
      get { return _capacity; }
      set { _capacity = value; }
    }

    private int _level = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private string _imageName = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"imageName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string imageName
    {
      get { return _imageName; }
      set { _imageName = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"StructureFunction")]
    public enum StructureFunction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TOWN_HALL", Value=0)]
      TOWN_HALL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INCOME", Value=1)]
      INCOME = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STORAGE", Value=2)]
      STORAGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLACKSMITH", Value=3)]
      BLACKSMITH = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LIBRARY", Value=4)]
      LIBRARY = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUSION", Value=5)]
      FUSION = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DECORATION", Value=6)]
      DECORATION = 6
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}