//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserStructProto.proto
// Note: requires additional types generated from: CoordinateProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserStructProto")]
  public partial class UserStructProto : global::ProtoBuf.IExtensible
  {
    public UserStructProto() {}
    

    private int _userID = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userID
    {
      get { return _userID; }
      set { _userID = value; }
    }

    private int _structID = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"structID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structID
    {
      get { return _structID; }
      set { _structID = value; }
    }

    private int _structLevel = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"structLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int structLevel
    {
      get { return _structLevel; }
      set { _structLevel = value; }
    }

    private proto.CoordinateProto _position = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.CoordinateProto position
    {
      get { return _position; }
      set { _position = value; }
    }

    private int _contents = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"contents", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int contents
    {
      get { return _contents; }
      set { _contents = value; }
    }

    private long _lastCollectTime = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lastCollectTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastCollectTime
    {
      get { return _lastCollectTime; }
      set { _lastCollectTime = value; }
    }

    private long _purchaseTime = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"purchaseTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long purchaseTime
    {
      get { return _purchaseTime; }
      set { _purchaseTime = value; }
    }

    private long _lastUpgradeTime = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"lastUpgradeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long lastUpgradeTime
    {
      get { return _lastUpgradeTime; }
      set { _lastUpgradeTime = value; }
    }

    private long _startUpgradeTime = default(long);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"startUpgradeTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long startUpgradeTime
    {
      get { return _startUpgradeTime; }
      set { _startUpgradeTime = value; }
    }

    private bool _isUpgrading = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"isUpgrading", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isUpgrading
    {
      get { return _isUpgrading; }
      set { _isUpgrading = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}