//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserDungeonStatusProto.proto
// Note: requires additional types generated from: FullUserProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserDungeonStatusRequestProto")]
  public partial class UserDungeonStatusRequestProto : global::ProtoBuf.IExtensible
  {
    public UserDungeonStatusRequestProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private int _userHp = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userHp
    {
      get { return _userHp; }
      set { _userHp = value; }
    }

    private int _userMana = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"userMana", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userMana
    {
      get { return _userMana; }
      set { _userMana = value; }
    }

    private int _actionsPerformed = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"actionsPerformed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int actionsPerformed
    {
      get { return _actionsPerformed; }
      set { _actionsPerformed = value; }
    }

    private string _dungeonRoomName = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dungeonRoomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dungeonRoomName
    {
      get { return _dungeonRoomName; }
      set { _dungeonRoomName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserDungeonStatusResponseProto")]
  public partial class UserDungeonStatusResponseProto : global::ProtoBuf.IExtensible
  {
    public UserDungeonStatusResponseProto() {}
    

    private proto.MinimumUserProto _mup = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mup", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public proto.MinimumUserProto mup
    {
      get { return _mup; }
      set { _mup = value; }
    }

    private proto.UserDungeonStatusResponseProto.UserDungeonStatusStatus _status = proto.UserDungeonStatusResponseProto.UserDungeonStatusStatus.SUCCESS;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(proto.UserDungeonStatusResponseProto.UserDungeonStatusStatus.SUCCESS)]
    public proto.UserDungeonStatusResponseProto.UserDungeonStatusStatus status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"UserDungeonStatusStatus")]
    public enum UserDungeonStatusStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NEGATIVE_HP_OR_MANA", Value=1)]
      FAIL_NEGATIVE_HP_OR_MANA = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NO_ACTIONS_PERFORMED", Value=2)]
      FAIL_NO_ACTIONS_PERFORMED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_NO_MONSTER_DEFEATED", Value=3)]
      FAIL_NO_MONSTER_DEFEATED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL_OTHER", Value=4)]
      FAIL_OTHER = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}