//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserConsumableQueueProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserConsumableQueueProto")]
  public partial class UserConsumableQueueProto : global::ProtoBuf.IExtensible
  {
    public UserConsumableQueueProto() {}
    

    private string _userConsumableQueueID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userConsumableQueueID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userConsumableQueueID
    {
      get { return _userConsumableQueueID; }
      set { _userConsumableQueueID = value; }
    }

    private string _userID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userID
    {
      get { return _userID; }
      set { _userID = value; }
    }

    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private int _quantity = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"quantity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quantity
    {
      get { return _quantity; }
      set { _quantity = value; }
    }

    private long _expectedStartMillis = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"expectedStartMillis", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long expectedStartMillis
    {
      get { return _expectedStartMillis; }
      set { _expectedStartMillis = value; }
    }

    private long _queuedTimeMillis = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"queuedTimeMillis", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long queuedTimeMillis
    {
      get { return _queuedTimeMillis; }
      set { _queuedTimeMillis = value; }
    }

    private bool _isFinishedBuilding = default(bool);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"isFinishedBuilding", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isFinishedBuilding
    {
      get { return _isFinishedBuilding; }
      set { _isFinishedBuilding = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}