//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserEquipmentProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserEquipmentProto")]
  public partial class UserEquipmentProto : global::ProtoBuf.IExtensible
  {
    public UserEquipmentProto() {}
    

    private string _userEquipID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userEquipID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userEquipID
    {
      get { return _userEquipID; }
      set { _userEquipID = value; }
    }

    private string _userID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userID
    {
      get { return _userID; }
      set { _userID = value; }
    }

    private string _equipID = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"equipID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string equipID
    {
      get { return _equipID; }
      set { _equipID = value; }
    }

    private int _equipLevel = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"equipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipLevel
    {
      get { return _equipLevel; }
      set { _equipLevel = value; }
    }

    private int _currDurability = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"currDurability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int currDurability
    {
      get { return _currDurability; }
      set { _currDurability = value; }
    }

    private bool _equipped = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"equipped", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool equipped
    {
      get { return _equipped; }
      set { _equipped = value; }
    }

    private long _timeAcquired = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"timeAcquired", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timeAcquired
    {
      get { return _timeAcquired; }
      set { _timeAcquired = value; }
    }

    private int _levelOfUserWhenAcquired = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"levelOfUserWhenAcquired", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int levelOfUserWhenAcquired
    {
      get { return _levelOfUserWhenAcquired; }
      set { _levelOfUserWhenAcquired = value; }
    }

    private string _dungeonRoomOrChestAcquiredFrom = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"dungeonRoomOrChestAcquiredFrom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dungeonRoomOrChestAcquiredFrom
    {
      get { return _dungeonRoomOrChestAcquiredFrom; }
      set { _dungeonRoomOrChestAcquiredFrom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}