//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: UserEquipRepairProto.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserEquipRepairProto")]
  public partial class UserEquipRepairProto : global::ProtoBuf.IExtensible
  {
    public UserEquipRepairProto() {}
    

    private string _userEquipRepairID = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userEquipRepairID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userEquipRepairID
    {
      get { return _userEquipRepairID; }
      set { _userEquipRepairID = value; }
    }

    private string _userID = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userID
    {
      get { return _userID; }
      set { _userID = value; }
    }

    private string _equipID = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"equipID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string equipID
    {
      get { return _equipID; }
      set { _equipID = value; }
    }

    private int _equipLevel = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"equipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int equipLevel
    {
      get { return _equipLevel; }
      set { _equipLevel = value; }
    }

    private int _durability = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"durability", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int durability
    {
      get { return _durability; }
      set { _durability = value; }
    }

    private long _expectedStartMillis = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"expectedStartMillis", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long expectedStartMillis
    {
      get { return _expectedStartMillis; }
      set { _expectedStartMillis = value; }
    }

    private long _queuedTimeMillis = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"queuedTimeMillis", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long queuedTimeMillis
    {
      get { return _queuedTimeMillis; }
      set { _queuedTimeMillis = value; }
    }

    private long _timeAcquired = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"timeAcquired", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long timeAcquired
    {
      get { return _timeAcquired; }
      set { _timeAcquired = value; }
    }

    private int _levelOfUserWhenAcquired = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"levelOfUserWhenAcquired", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int levelOfUserWhenAcquired
    {
      get { return _levelOfUserWhenAcquired; }
      set { _levelOfUserWhenAcquired = value; }
    }

    private string _dungeonRoomOrChestAcquiredFrom = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"dungeonRoomOrChestAcquiredFrom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string dungeonRoomOrChestAcquiredFrom
    {
      get { return _dungeonRoomOrChestAcquiredFrom; }
      set { _dungeonRoomOrChestAcquiredFrom = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}